name: swipetune
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
 
  sdk: '>=3.2.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.7.0 

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_native_splash: ^2.4.6
  app_links: ^6.4.1
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.2
  http: ^1.5.0
  provider: ^6.1.2
  just_audio: ^0.10.5
  cached_network_image: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  cloud_firestore: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#000000" 
  image: assets/logo.png
  branding: assets/swipetune_text.png
